import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();

export const loadPresetCatalog = () =>
  JSON.parse(fs.readFileSync(path.join(root, 'presets/video-presets.json'), 'utf8'));

export const loadThemeCatalog = () =>
  JSON.parse(fs.readFileSync(path.join(root, 'themes/catalog.json'), 'utf8'));

export const createProjectManifest = ({
  id,
  title,
  preset = 'landscape-16x9',
  theme = 'default-dark',
  outputFile,
}) => {
  const presets = loadPresetCatalog();
  const themes = loadThemeCatalog();
  const profile = presets[preset];

  if (!/^[a-z0-9][a-z0-9-]*$/.test(id)) {
    throw new Error('Project id must use lowercase letters, numbers and hyphens only');
  }
  if (!profile) throw new Error(`Unknown video preset: ${preset}`);
  if (!themes[theme]) throw new Error(`Unknown video theme: ${theme}`);

  return {
    version: 1,
    id,
    title,
    engine: 'remotion',
    compositionId: 'ProductDemo',
    theme,
    output: {
      width: profile.width,
      height: profile.height,
      fps: profile.fps,
      format: 'mp4',
      file: outputFile ?? `output/${id}.mp4`,
    },
    data: {
      inline: {
        product: title,
        preset,
        theme,
      },
    },
    scenes: [
      {
        id: 'intro',
        type: 'hero',
        durationSeconds: 2,
        payload: {
          eyebrow: 'VIDEO STUDIO PROJECT',
          title,
          subtitle: `${preset} · ${theme}`,
        },
      },
      {
        id: 'capabilities',
        type: 'capability-grid',
        durationSeconds: 4,
        payload: {
          items: [
            'Manifest-driven',
            'Reusable scenes',
            'Theme packs',
            'Data adapters',
            'CI rendering',
            'Multi-format',
          ],
        },
      },
      {
        id: 'outro',
        type: 'outro',
        durationSeconds: 2,
        payload: {
          title: 'Generated by Video Studio',
        },
      },
    ],
  };
};

export const writeProject = ({
  id,
  title,
  preset,
  theme,
  outputRoot = 'projects',
  force = false,
  outputFile,
}) => {
  const manifest = createProjectManifest({id, title, preset, theme, outputFile});
  const projectDir = path.resolve(outputRoot, id);
  const projectFile = path.join(projectDir, 'project.json');

  if (fs.existsSync(projectFile) && !force) {
    throw new Error(`Project already exists: ${projectFile}. Use --force to overwrite.`);
  }

  fs.mkdirSync(projectDir, {recursive: true});
  fs.writeFileSync(projectFile, JSON.stringify(manifest, null, 2) + '\n');
  return {manifest, projectDir, projectFile};
};
